import firebase_admin
from firebase_admin import credentials, firestore
import re
from datetime import datetime, timezone

# 🔐 Firebase Init
cred = credentials.Certificate("firebase-key.json")
firebase_admin.initialize_app(cred)
db = firestore.client()

# ✅ 25 Real, Diverse Scholarships (across India)
scholarships = [
    {
        "name": "AICTE Pragati Scholarship for Girls",
        "amount": "₹50,000",
        "deadline": "2025-08-31",
        "gender": "Female",
        "education": "UG",
        "category": "GEN",
        "state": "All",
        "max_income": 800000,
        "religion": "Any",
        "disability": "Any",
        "min_percentage": 0,
        "apply_link": "https://aicte-india.org"
    },
    {
        "name": "Post Matric Scholarship for SC Students",
        "amount": "₹25,000",
        "deadline": "2025-07-30",
        "gender": "Any",
        "education": "12th",
        "category": "SC",
        "state": "All",
        "max_income": 250000,
        "religion": "Any",
        "disability": "Any",
        "min_percentage": 60,
        "apply_link": "https://scholarships.gov.in"
    },
    {
        "name": "INSPIRE Scholarship by DST",
        "amount": "₹80,000",
        "deadline": "2025-09-15",
        "gender": "Any",
        "education": "UG",
        "category": "GEN",
        "state": "All",
        "max_income": 800000,
        "religion": "Any",
        "disability": "Any",
        "min_percentage": 85,
        "apply_link": "https://online-inspire.gov.in"
    },
    {
        "name": "Tata Capital Pankh Scholarship",
        "amount": "₹30,000",
        "deadline": "2025-09-01",
        "gender": "Any",
        "education": "UG",
        "category": "EWS",
        "state": "All",
        "max_income": 400000,
        "religion": "Any",
        "disability": "No",
        "min_percentage": 70,
        "apply_link": "https://www.tatacapital.com/pankh"
    },
    {
        "name": "Vidyasaarathi UG Scholarship",
        "amount": "₹25,000",
        "deadline": "2025-08-10",
        "gender": "Any",
        "education": "UG",
        "category": "OBC",
        "state": "Maharashtra",
        "max_income": 300000,
        "religion": "Any",
        "disability": "No",
        "min_percentage": 70,
        "apply_link": "https://www.vidyasaarathi.co.in"
    },
    {
        "name": "Ishan Uday Special Scholarship (NER)",
        "amount": "₹54,000",
        "deadline": "2025-09-10",
        "gender": "Any",
        "education": "UG",
        "category": "GEN",
        "state": "Assam",
        "max_income": 450000,
        "religion": "Any",
        "disability": "Any",
        "min_percentage": 65,
        "apply_link": "https://ugc.ac.in/ner/"
    },
    {
        "name": "SNL Bearings Scholarship",
        "amount": "₹15,000",
        "deadline": "2025-07-28",
        "gender": "Any",
        "education": "UG",
        "category": "GEN",
        "state": "Jharkhand",
        "max_income": 500000,
        "religion": "Any",
        "disability": "Any",
        "min_percentage": 60,
        "apply_link": "https://www.buddy4study.com"
    },
    {
        "name": "UGC Indira Gandhi Single Girl Child Scholarship",
        "amount": "₹36,200",
        "deadline": "2025-08-30",
        "gender": "Female",
        "education": "PG",
        "category": "GEN",
        "state": "All",
        "max_income": 800000,
        "religion": "Any",
        "disability": "Any",
        "min_percentage": 65,
        "apply_link": "https://scholarships.gov.in"
    },
    {
        "name": "Pre-Matric Scholarship for Minority Students",
        "amount": "₹10,000",
        "deadline": "2025-07-31",
        "gender": "Any",
        "education": "8th",
        "category": "Minority",
        "state": "Any",
        "max_income": 200000,
        "religion": "Muslim",
        "disability": "Any",
        "min_percentage": 50,
        "apply_link": "https://minorityaffairs.gov.in"
    },
    {
        "name": "Saksham Scholarship for Differently Abled Students",
        "amount": "₹50,000",
        "deadline": "2025-08-31",
        "gender": "Any",
        "education": "UG",
        "category": "GEN",
        "state": "All",
        "max_income": 800000,
        "religion": "Any",
        "disability": "Yes",
        "min_percentage": 55,
        "apply_link": "https://aicte-india.org"
    },
    # Add 15 more entries (next message to keep readable)
        {
        "name": "HDFC Educational Crisis Scholarship",
        "amount": "₹25,000",
        "deadline": "2025-09-10",
        "gender": "Any",
        "education": "10th",
        "category": "EWS",
        "state": "All",
        "max_income": 360000,
        "religion": "Any",
        "disability": "Any",
        "min_percentage": 55,
        "apply_link": "https://www.hdfcbank.com/scholarship"
    },
    {
        "name": "L&T Build India Scholarship",
        "amount": "₹1,80,000",
        "deadline": "2025-09-05",
        "gender": "Any",
        "education": "UG",
        "category": "GEN",
        "state": "All",
        "max_income": 800000,
        "religion": "Any",
        "disability": "Any",
        "min_percentage": 70,
        "apply_link": "https://www.lntecc.com"
    },
    {
        "name": "ONGC Scholarship for SC/ST",
        "amount": "₹48,000",
        "deadline": "2025-08-28",
        "gender": "Any",
        "education": "UG",
        "category": "SC",
        "state": "All",
        "max_income": 450000,
        "religion": "Any",
        "disability": "Any",
        "min_percentage": 60,
        "apply_link": "https://ongcindia.com"
    },
    {
        "name": "Maulana Azad Scholarship for Minority Girls",
        "amount": "₹12,000",
        "deadline": "2025-07-31",
        "gender": "Female",
        "education": "12th",
        "category": "Minority",
        "state": "All",
        "max_income": 200000,
        "religion": "Muslim",
        "disability": "Any",
        "min_percentage": 60,
        "apply_link": "https://maef.nic.in"
    },
    {
        "name": "Bihar Post Matric Scholarship for EBC",
        "amount": "₹20,000",
        "deadline": "2025-08-20",
        "gender": "Any",
        "education": "12th",
        "category": "OBC",
        "state": "Bihar",
        "max_income": 300000,
        "religion": "Any",
        "disability": "Any",
        "min_percentage": 50,
        "apply_link": "https://pmsonline.bih.nic.in"
    },
    {
        "name": "Dr. Ambedkar Scholarship for Punjab SC Students",
        "amount": "₹30,000",
        "deadline": "2025-08-15",
        "gender": "Any",
        "education": "UG",
        "category": "SC",
        "state": "Punjab",
        "max_income": 250000,
        "religion": "Any",
        "disability": "Any",
        "min_percentage": 60,
        "apply_link": "https://punjabscholarships.gov.in"
    },
    {
        "name": "Sitaram Jindal Foundation Scholarship",
        "amount": "₹25,000",
        "deadline": "2025-07-25",
        "gender": "Any",
        "education": "UG",
        "category": "GEN",
        "state": "All",
        "max_income": 480000,
        "religion": "Any",
        "disability": "Any",
        "min_percentage": 65,
        "apply_link": "https://sjfoundation.org"
    },
    {
        "name": "Kind Scholarship for Young Women",
        "amount": "₹20,000",
        "deadline": "2025-08-22",
        "gender": "Female",
        "education": "UG",
        "category": "EWS",
        "state": "All",
        "max_income": 400000,
        "religion": "Any",
        "disability": "No",
        "min_percentage": 70,
        "apply_link": "https://www.buddy4study.com"
    },
    {
        "name": "Jharkhand e-Kalyan Scholarship",
        "amount": "₹25,000",
        "deadline": "2025-08-18",
        "gender": "Any",
        "education": "12th",
        "category": "SC",
        "state": "Jharkhand",
        "max_income": 250000,
        "religion": "Any",
        "disability": "Any",
        "min_percentage": 60,
        "apply_link": "https://ekalyan.cgg.gov.in"
    },
    {
        "name": "Swami Vivekananda Merit Scholarship – West Bengal",
        "amount": "₹18,000",
        "deadline": "2025-07-30",
        "gender": "Any",
        "education": "12th",
        "category": "GEN",
        "state": "West Bengal",
        "max_income": 250000,
        "religion": "Any",
        "disability": "Any",
        "min_percentage": 60,
        "apply_link": "https://svmcm.wbhed.gov.in"
    },
    {
        "name": "Fair and Lovely Foundation Scholarship",
        "amount": "₹25,000",
        "deadline": "2025-08-26",
        "gender": "Female",
        "education": "UG",
        "category": "GEN",
        "state": "All",
        "max_income": 600000,
        "religion": "Any",
        "disability": "Any",
        "min_percentage": 65,
        "apply_link": "https://www.buddy4study.com"
    },
    {
        "name": "Colgate Keep India Smiling Scholarship",
        "amount": "₹20,000",
        "deadline": "2025-07-29",
        "gender": "Any",
        "education": "10th",
        "category": "Any",
        "state": "All",
        "max_income": 500000,
        "religion": "Any",
        "disability": "Any",
        "min_percentage": 70,
        "apply_link": "https://www.buddy4study.com"
    },
    {
        "name": "Credit Suisse Scholarship for Engineering Students",
        "amount": "₹1,00,000",
        "deadline": "2025-09-01",
        "gender": "Any",
        "education": "UG",
        "category": "GEN",
        "state": "Maharashtra",
        "max_income": 500000,
        "religion": "Any",
        "disability": "No",
        "min_percentage": 75,
        "apply_link": "https://www.buddy4study.com"
    },
    {
        "name": "MahaDBT Post Matric Scholarship – Maharashtra",
        "amount": "₹35,000",
        "deadline": "2025-08-21",
        "gender": "Any",
        "education": "UG",
        "category": "OBC",
        "state": "Maharashtra",
        "max_income": 250000,
        "religion": "Any",
        "disability": "Any",
        "min_percentage": 50,
        "apply_link": "https://mahadbtmahait.gov.in"
    },
    {
        "name": "LIC Golden Jubilee Scholarship",
        "amount": "₹20,000",
        "deadline": "2025-09-12",
        "gender": "Any",
        "education": "UG",
        "category": "EWS",
        "state": "All",
        "max_income": 200000,
        "religion": "Any",
        "disability": "Any",
        "min_percentage": 60,
        "apply_link": "https://licindia.in"
    },
        {
        "name": "Medhaavi Engineering Scholarship",
        "amount": "₹50,000",
        "deadline": "2025-08-15",
        "gender": "Any",
        "education": "UG",
        "category": "GEN",
        "state": "Karnataka",
        "max_income": 500000,
        "religion": "Any",
        "disability": "No",
        "min_percentage": 80,
        "apply_link": "https://www.buddy4study.com"
    },
    {
        "name": "Rajarshi Shahu Maharaj Scholarship – Maharashtra",
        "amount": "₹30,000",
        "deadline": "2025-07-25",
        "gender": "Any",
        "education": "UG",
        "category": "SC",
        "state": "Maharashtra",
        "max_income": 250000,
        "religion": "Any",
        "disability": "Any",
        "min_percentage": 50,
        "apply_link": "https://mahadbtmahait.gov.in"
    },
    {
        "name": "West Bengal Post Matric Scholarship for SC/ST/OBC",
        "amount": "₹18,000",
        "deadline": "2025-08-05",
        "gender": "Any",
        "education": "UG",
        "category": "OBC",
        "state": "West Bengal",
        "max_income": 250000,
        "religion": "Any",
        "disability": "Any",
        "min_percentage": 55,
        "apply_link": "https://wbmdfcscholarship.org"
    },
    {
        "name": "M-Scholarship for 10th Passed Students",
        "amount": "₹10,000",
        "deadline": "2025-07-28",
        "gender": "Any",
        "education": "10th",
        "category": "GEN",
        "state": "All",
        "max_income": 300000,
        "religion": "Any",
        "disability": "No",
        "min_percentage": 75,
        "apply_link": "https://www.vidyasaarathi.co.in"
    },
    {
        "name": "National Means-cum-Merit Scholarship",
        "amount": "₹12,000",
        "deadline": "2025-09-15",
        "gender": "Any",
        "education": "8th",
        "category": "EWS",
        "state": "All",
        "max_income": 150000,
        "religion": "Any",
        "disability": "Any",
        "min_percentage": 55,
        "apply_link": "https://scholarships.gov.in"
    },
    {
        "name": "Keep India Smiling Dental Scholarship",
        "amount": "₹50,000",
        "deadline": "2025-08-22",
        "gender": "Any",
        "education": "PG",
        "category": "GEN",
        "state": "All",
        "max_income": 600000,
        "religion": "Any",
        "disability": "No",
        "min_percentage": 70,
        "apply_link": "https://www.buddy4study.com"
    },
    {
        "name": "Mother Teresa Scholarship – Kerala",
        "amount": "₹15,000",
        "deadline": "2025-08-10",
        "gender": "Any",
        "education": "UG",
        "category": "Minority",
        "state": "Kerala",
        "max_income": 200000,
        "religion": "Christian",
        "disability": "Any",
        "min_percentage": 60,
        "apply_link": "https://dcescholarship.kerala.gov.in"
    },
    {
        "name": "ePASS Scholarship – Andhra Pradesh",
        "amount": "₹35,000",
        "deadline": "2025-08-18",
        "gender": "Any",
        "education": "UG",
        "category": "SC",
        "state": "Andhra Pradesh",
        "max_income": 250000,
        "religion": "Any",
        "disability": "Any",
        "min_percentage": 55,
        "apply_link": "https://epass.apcfss.in"
    },
    {
        "name": "Sambhava Foundation Scholarship",
        "amount": "₹20,000",
        "deadline": "2025-08-21",
        "gender": "Any",
        "education": "12th",
        "category": "OBC",
        "state": "All",
        "max_income": 350000,
        "religion": "Any",
        "disability": "Any",
        "min_percentage": 65,
        "apply_link": "https://www.buddy4study.com"
    },
    {
        "name": "Tata Housing Scholarship for Meritorious Girl Students",
        "amount": "₹60,000",
        "deadline": "2025-08-25",
        "gender": "Female",
        "education": "UG",
        "category": "EWS",
        "state": "All",
        "max_income": 300000,
        "religion": "Any",
        "disability": "Any",
        "min_percentage": 75,
        "apply_link": "https://www.buddy4study.com"
    },
    {
        "name": "ONGC Scholarship for OBC Students",
        "amount": "₹48,000",
        "deadline": "2025-08-26",
        "gender": "Any",
        "education": "PG",
        "category": "OBC",
        "state": "All",
        "max_income": 200000,
        "religion": "Any",
        "disability": "Any",
        "min_percentage": 60,
        "apply_link": "https://ongcindia.com"
    },
    {
        "name": "Aditya Birla Scholarship",
        "amount": "₹65,000",
        "deadline": "2025-09-10",
        "gender": "Any",
        "education": "UG",
        "category": "GEN",
        "state": "All",
        "max_income": 600000,
        "religion": "Any",
        "disability": "No",
        "min_percentage": 85,
        "apply_link": "https://www.adityabirlascholars.net"
    },
    {
        "name": "Pre-Matric Disability Scholarship",
        "amount": "₹20,000",
        "deadline": "2025-08-20",
        "gender": "Any",
        "education": "10th",
        "category": "GEN",
        "state": "All",
        "max_income": 250000,
        "religion": "Any",
        "disability": "Yes",
        "min_percentage": 45,
        "apply_link": "https://scholarships.gov.in"
    },
    {
        "name": "ONGC Scholarship for Girls in Engineering",
        "amount": "₹48,000",
        "deadline": "2025-08-19",
        "gender": "Female",
        "education": "UG",
        "category": "GEN",
        "state": "All",
        "max_income": 450000,
        "religion": "Any",
        "disability": "No",
        "min_percentage": 70,
        "apply_link": "https://ongcindia.com"
    },
    {
        "name": "Nirman Shramik Kalyan Yojana (Odisha)",
        "amount": "₹20,000",
        "deadline": "2025-08-29",
        "gender": "Any",
        "education": "10th",
        "category": "GEN",
        "state": "Odisha",
        "max_income": 200000,
        "religion": "Any",
        "disability": "Any",
        "min_percentage": 50,
        "apply_link": "https://scholarship.odisha.gov.in"
    },
    {
    "name": "Andhra Pradesh OBC Christian Merit Scholarship",
    "amount": "₹20,000",
    "deadline": "2025-07-31",
    "gender": "Male",
    "education": "9th",
    "category": "OBC",
    "state": "Andhra Pradesh",
    "max_income": 300000,
    "religion": "Christian",
    "disability": "No",
    "min_percentage": 70,
    "apply_link": "https://scholarships.ap.gov.in/apply-now",
    "created_at": datetime.utcnow().isoformat()
},
{
    "name": "Pre-Matric Scholarship for OBC Students",
    "amount": "₹10,000",
    "deadline": "2025-08-25",
    "gender": "Any",
    "education": "9th",
    "category": "OBC",
    "state": "Andhra Pradesh",
    "max_income": 250000,
    "religion": "Any",
    "disability": "Any",
    "min_percentage": 60,
    "apply_link": "https://scholarships.gov.in",
    "created_at": datetime.now(timezone.utc).isoformat()
}



]

# Upload to Firestore
def clean_id(name):
    return re.sub(r'[^\w\s-]', '', name).replace(" ", "_").lower()

# 🔁 Upload
for s in scholarships:
    doc_id = clean_id(s['name'])
    db.collection("scholarships").document(doc_id).set(s)

print("✅ Re-uploaded with unique IDs successfully.")
